name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test-std:
    name: "Test (std)"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Rust dependency cache
        uses: Swatinem/rust-cache@v2
      - name: Compile and run tests
        run: cargo test --no-fail-fast

  test-no-std:
    name: "Test (no_std)"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Rust dependency cache
        uses: Swatinem/rust-cache@v2
      - name: Compile and run tests
        run: cargo test -p rapidhash --no-fail-fast --lib --tests --no-default-features

  test-unsafe:
    name: "Test (unsafe)"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Rust dependency cache
        uses: Swatinem/rust-cache@v2
      - name: Compile and run tests
        run: cargo test -p rapidhash --no-fail-fast --lib --tests --features=unsafe

  test-all-features:
    name: "Test (all features)"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Rust dependency cache
        uses: Swatinem/rust-cache@v2
      - name: Compile and run tests
        run: cargo test -p rapidhash --no-fail-fast --lib --tests --all-features

  test-msrv:
    name: "Test (MSRV)"
    runs-on: ubuntu-latest
    env:
      RUST_VERSION: 1.77.0
    steps:
      - uses: actions/checkout@v4
      - name: Rust dependency cache
        uses: Swatinem/rust-cache@v2
      - name: Install Rust (rustup, ${{ env.RUST_VERSION }})
        shell: bash
        run: rustup update ${{ env.RUST_VERSION }} --no-self-update && rustup default ${{ env.RUST_VERSION }} && cargo -V && rustc -V
      - name: Compile and run tests (std)
        run: cargo test -p rapidhash --no-fail-fast --all-features
      - name: Compile and run tests (no_std)
        run: cargo test -p rapidhash --no-fail-fast --lib --tests --no-default-features

  test-c:
    name: "Test (C implementations)"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Rust dependency cache
        uses: Swatinem/rust-cache@v2
      - name: Compile and run tests
        run: cargo test -p rapidhash-c --no-fail-fast

  test-docs:
    name: "Test (docs)"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Rust dependency cache
        uses: Swatinem/rust-cache@v2
      - name: Compile and run tests
        run: RUSTDOCFLAGS="--cfg docsrs" cargo +nightly test -p rapidhash --all-features --doc --no-fail-fast

  test-wasm:
    # Test compiling for the webassembly target with default features.
    name: "Test (wasm)"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Rust dependency cache
        uses: Swatinem/rust-cache@v2
      - name: Install wasm target
        run: rustup target add wasm32-unknown-unknown
      - name: Compile and run tests
        run: cargo build -p rapidhash --target wasm32-unknown-unknown
