name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test-std:
    name: "Test (std)"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Rust dependency cache
      uses: Swatinem/rust-cache@v2
    - name: Compile and run tests
      run: cargo test --no-fail-fast --all-features

  test-no-std:
    name: "Test (no_std)"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Rust dependency cache
        uses: Swatinem/rust-cache@v2
      - name: Compile and run tests
        run: cargo test -p rapidhash --no-fail-fast --lib --no-default-features --features=v1,v2

  test-unsafe:
    name: "Test (unsafe)"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Rust dependency cache
        uses: Swatinem/rust-cache@v2
      - name: Compile and run tests
        run: cargo test -p rapidhash --no-fail-fast --lib --no-default-features --features v1,v2,unsafe

  test-msrv:
    name: "Test (MSRV)"
    runs-on: ubuntu-latest
    env:
      RUST_VERSION: 1.77.0
    steps:
      - uses: actions/checkout@v4
      - name: Rust dependency cache
        uses: Swatinem/rust-cache@v2
      - name: Install Rust (rustup, ${{ env.RUST_VERSION }})
        run: rustup update ${{ env.RUST_VERSION }} --no-self-update && rustup default ${{ env.RUST_VERSION }} && cargo -V && rustc -V
        shell: bash
      - name: Compile and run tests (std)
        run: cargo test --no-fail-fast --all-features
      - name: Compile and run tests (no_std)
        run: cargo test -p rapidhash --no-fail-fast --lib --no-default-features --features=std,v1,v2,vlatest

  test-c:
    name: "Test (C implementations)"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Rust dependency cache
        uses: Swatinem/rust-cache@v2
      - name: Compile and run tests
        run: cargo test -p rapidhash-c --no-fail-fast

  test-v1:
    name: "Test (v1)"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Rust dependency cache
        uses: Swatinem/rust-cache@v2
      - name: Compile and run tests
        run: cargo test -p rapidhash --no-fail-fast --no-default-features --features=std,v1

  test-v2:
    name: "Test (v2)"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Rust dependency cache
        uses: Swatinem/rust-cache@v2
      - name: Compile and run tests
        run: cargo test -p rapidhash --no-fail-fast --no-default-features --features=std,v2
